package com.ruoyi.business.demo.mapper;

import com.ruoyi.business.demo.domain.Jc41Item;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface Jc41ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc41_item
     *
     * @mbg.generated Mon Oct 28 14:40:34 UTC 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc41_item
     *
     * @mbg.generated Mon Oct 28 14:40:34 UTC 2024
     */
    int insert(Jc41Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc41_item
     *
     * @mbg.generated Mon Oct 28 14:40:34 UTC 2024
     */
    int insertSelective(Jc41Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc41_item
     *
     * @mbg.generated Mon Oct 28 14:40:34 UTC 2024
     */
    Jc41Item selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc41_item
     *
     * @mbg.generated Mon Oct 28 14:40:34 UTC 2024
     */
    int updateByPrimaryKeySelective(Jc41Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc41_item
     *
     * @mbg.generated Mon Oct 28 14:40:34 UTC 2024
     */
    int updateById(Jc41Item record);
}